---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: all
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    # - verify
    - destroy
platforms:
  - name: apps-wazuh-manager-ubuntu18
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:ubuntu18
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    capabilities: ['NET_ADMIN']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-manager-ubuntu20
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:ubuntu20
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    capabilities: ['NET_ADMIN']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: apps-wazuh-manager-ubuntu22
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:ubuntu22
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-manager-debian10
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian10
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: apps-wazuh-manager-debian11
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian11
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3
  - name: apps-wazuh-manager-debian12
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian12
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - python3

provisioner:
  name: ansible
  connection_options:
    ansible_remote_tmp: /tmp
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      bullseye:
        ansible_python_interpreter: "/usr/bin/python3.9"
      bookworm:
        ansible_python_interpreter: "/usr/bin/python3.9"

verifier:
  name: ansible
