---
- name: "Install requierements"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success
  with_items:
    - apt-transport-https
    - lsb-release
    - gnupg2

- name: "Add wazuh apt signing key"
  ansible.builtin.apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: "Add wazuh repo to apt list"
  ansible.builtin.apt_repository:
    repo: deb https://packages.wazuh.com/4.x/apt/ stable main
    state: present
    filename: wazuh

- name: "Install wazuh-manager"
  ansible.builtin.package:
    name: wazuh-manager
    state: present
    update_cache: true
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success

- name: "Start wazuh-manager services"
  ansible.builtin.service:
    name: wazuh-manager
    state: started
    enabled: true
